package subota.max.core.event;

public enum DomainEventType {
    VERIFICATION_CREATED,
    VERIFICATION_CONFIRMED,
    VERIFICATION_CONFIRMATION_FAILED,
    VERIFICATION_EXPIRED,

    NOTIFICATION_CREATED,
    NOTIFICATION_DISPATCHED
}
